### ISSUE TITLE
Crash on mint

### ISSUE THREAD

**Issue by itseasy21** [immutable/imx-integration-example#1]
Hi,

The app is crashing on the mint function. 
![mint-crash](https://user-images.githubusercontent.com/8541602/132977530-0bd18910-1190-4821-b66d-b33ce9462813.png)

**Comment by experteverever** [comment]
Did you solve this issue?

**Comment by itseasy21** [comment]
> Did you solve this issue?

Yup, if you are still facing this issue check you provider variable to be not null
