### ISSUE TITLE
Compile error Type 'Wallet' is not assignable to type 'Signer' (inventory.tsx)

### ISSUE THREAD

**Issue by hershkoy** [immutable/imx-integration-example#12]
I am trying to run the repo. I cloned and installed the project as-is, and now I am getting this error:

```
imx-integration-example/src/Inventory.tsx
TypeScript error in imx-integration-example/src/Inventory.tsx(71,9):
Type 'Wallet' is not assignable to type 'Signer'.
  The types returned by 'provider.getBlock(...)' are incompatible between these types.
    Type 'Promise<import("imx-integration-example/node_modules/@ethersproject/abstract-provider/lib/index").Block>' is not assignable to type 'Promise<import("imx-integration-example/node_modules/@imtbl/imx-sdk/node_modules/@ethersproject/abstract-provider/lib/index").Block>'.
      Property '_difficulty' is missing in type 'import("imx-integration-example/node_modules/@ethersproject/abstract-provider/lib/index").Block' but required in type 'import("imx-integration-example/node_modules/@imtbl/imx-sdk/node_modules/@ethersproject/abstract-provider/lib/index").Block'.  TS2322

    69 |     const minterClient = await ImmutableXClient.build({
    70 |         publicApiUrl,
  > 71 |         signer: minter,
       |         ^
    72 |         starkContractAddress,
    73 |         registrationContractAddress,
    74 |     })

```

**Comment by hershkoy** [comment]
I think that there was a change that is causing this issue. 
In the docs:
[https://docs.x.immutable.com/docs/minting-assets-1](https://docs.x.immutable.com/docs/minting-assets-1)
code is using another library:

```
import { Wallet } from '@ethersproject/wallet';
const signer = new Wallet(process.env.PRIVATE_KEY!).connect(provider);
```

While this project is using:
```
import { ethers } from 'ethers';
const minter = new ethers.Wallet(minterPrivateKey).connect(provider);
```

How to convert the code?

**Comment by hershkoy** [comment]
This probably used to work in the past while 
```
import { ImmutableXClient } from '@imtbl/imx-link-lib';
```
was used. But now the client is coming from the sdk:
```
import { ... ImmutableXClient, ... } from '@imtbl/imx-sdk';
```

**Comment by hershkoy** [comment]
I have found the issue. The ethers version in the imx-sdk was 5.4.4 while in the react repo it was 5.4.6.
Changing the react to use 5.4.4 solved the issue

**Comment by KIMPANGDUCK** [comment]
> I have found the issue. The ethers version in the imx-sdk was 5.4.4 while in the react repo it was 5.4.6. Changing the react to use 5.4.4 solved the issue

I changed ethers version to 5.4.4 by using command yarn upgrade ethers@5.4.4 
it doesn't solve the issue.

**Comment by KIMPANGDUCK** [comment]
> > I have found the issue. The ethers version in the imx-sdk was 5.4.4 while in the react repo it was 5.4.6. Changing the react to use 5.4.4 solved the issue
> 
> I changed ethers version to 5.4.4 by using command yarn upgrade ethers@5.4.4 it doesn't solve the issue.

I changed the ethers version to 5.5.3 and it solved this issue but can't load the main page still.

**Comment by alcalawil** [comment]
solved same way
